#!/usr/bin/env python3
"""Sweep the ocha-dap GitHub org for NEW (or removed) repos since the last run.

Discovery, not drift: the drift checkers watch things already in the KB; this watches the org for
repos that have *appeared* (a new framework/pipeline/app spoke we should consider ingesting) or
*disappeared*. Same shape as check_infra_drift.py: fingerprint `gh repo list` → diff against a
committed baseline (`infrastructure/.repos-baseline.json`) → report the delta → advance the baseline
(its git history is the org changelog). Likely DS-team repos (`ds-*`, `pa-aa-*`, `ds-aa-*`) are
highlighted; everything else is listed quietly so nothing is silently missed.

Usage:  python scripts/check_new_repos.py [--report f.md] [--update-baseline]
Exit:   0 = no change (or first-run init) · 2 = at least one new/removed repo
Needs:  gh (authed to read the org), pyyaml not required.
"""
from __future__ import annotations
import argparse
import datetime as dt
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASELINE = ROOT / "infrastructure" / ".repos-baseline.json"
ORG = "ocha-dap"
# DS-team naming conventions → the new repos most likely worth ingesting.
# hdx-signals: DS-team repo outside the prefix convention (see check_coverage.EXTRA_SCOPE).
DS_RE = re.compile(r"^(ds-|pa-aa-|ds-aa-|hdx-signals$)", re.I)


def sh(args: list[str]) -> str:
    try:
        return subprocess.run(args, capture_output=True, text=True, timeout=120).stdout
    except Exception:
        return ""


def fingerprint() -> dict | None:
    """{repo_name: {created, visibility, description}} for the whole org. None if gh can't read it
    (→ skip, don't wipe the baseline)."""
    out = sh(["gh", "repo", "list", ORG, "--limit", "2000", "--json",
              "name,createdAt,visibility,description,isArchived"])
    if not out.strip():
        return None
    try:
        repos = json.loads(out)
    except json.JSONDecodeError:
        return None
    if not isinstance(repos, list) or not repos:
        return None
    return {r["name"]: {"created": (r.get("createdAt") or "")[:10],
                        "visibility": r.get("visibility"),
                        "archived": r.get("isArchived", False),
                        "desc": (r.get("description") or "").strip()} for r in repos}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--report")
    ap.add_argument("--update-baseline", action="store_true")
    ap.add_argument("--emit-new", metavar="PATH", help="write newline-separated new repo names")
    args = ap.parse_args()

    now = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    fp = fingerprint()
    base = {}
    if BASELINE.exists():
        try:
            base = json.loads(BASELINE.read_text()).get("repos", {})
        except json.JSONDecodeError:
            base = {}
    first_run = not base

    lines = ["# KB new-repo sweep", "",
             f"_Generated by `scripts/check_new_repos.py` — {now}._  ",
             f"_`{ORG}` org vs committed baseline (`infrastructure/.repos-baseline.json`)._", ""]
    added = removed = []
    if fp is None:
        lines += ["> ⏭️ **SKIPPED** — `gh repo list` returned nothing (auth?). Not checked this run."]
    elif first_run:
        lines += [f"_Baseline initialised with {len(fp)} repos (no prior baseline to diff)._"]
    else:
        added = sorted(k for k in fp if k not in base)
        removed = sorted(k for k in base if k not in fp)
        if not (added or removed):
            lines += [f"✅ No new or removed repos ({len(fp)} total)."]
        else:
            ds_new = [r for r in added if DS_RE.match(r)]
            other_new = [r for r in added if not DS_RE.match(r)]
            if ds_new:
                lines += [f"## 🆕 New DS-team repos ({len(ds_new)}) — candidates to ingest", "",
                          "| repo | created | vis | description |", "|---|---|---|---|"]
                lines += [f"| [`{r}`](https://github.com/{ORG}/{r}) | {fp[r]['created']} | "
                          f"{fp[r]['visibility']} | {fp[r]['desc'][:80]} |" for r in ds_new]
                lines += ["", "_To ingest: `gh workflow run kb-ingest.yml -f kind=<app|pipeline> -f target=<name>` "
                          "(frameworks need the PDF ingest)._", ""]
            if other_new:
                lines += [f"<details><summary>🆕 Other new org repos ({len(other_new)})</summary>", "",
                          "| repo | created | vis |", "|---|---|---|"]
                lines += [f"| [`{r}`](https://github.com/{ORG}/{r}) | {fp[r]['created']} | {fp[r]['visibility']} |"
                          for r in other_new]
                lines += ["", "</details>", ""]
            if removed:
                lines += [f"## 🗑️ Removed/renamed ({len(removed)})", ""] + [f"- `{r}`" for r in removed] + [""]

    report = "\n".join(lines) + "\n"
    print(report)
    if args.report:
        Path(args.report).write_text(report, encoding="utf-8")
    if args.emit_new:
        Path(args.emit_new).write_text("\n".join(added), encoding="utf-8")
    if args.update_baseline and fp is not None:
        BASELINE.write_text(json.dumps({"generated": now, "repos": fp}, indent=2, sort_keys=True) + "\n",
                            encoding="utf-8")
    sys.exit(2 if (not first_run and fp is not None and (added or removed)) else 0)


if __name__ == "__main__":
    main()
