#!/usr/bin/env python3
"""Deterministic drift check for the KB's *how-it-works* docs (the meta-docs).

The content layer self-maintains (drift / freshness / discovery → kb-ingest). The
meta-docs — DESIGN, ROADMAP, INGESTION, automation, the READMEs — had no detector
and rotted silently (stale counts, dangling script refs). This is their drift axis.

It is the *mechanical* half (high-signal, no judgment); the prose-staleness half
(shipped phases still marked todo, superseded rationale) is the monthly Claude
audit in `docs-audit.yml`. Two checks here:

  MISSING-REF   a meta-doc mentions a `scripts/<x>.py|.sh` or `.github/workflows/<x>.yml`
                that no longer exists on disk (renamed/deleted but the doc still names it).
  STALE-COUNTS  a doc's <!-- COUNTS --> block disagrees with the live corpus
                (someone added pages but didn't run gen_doc_counts.py).
  STALE-INFRA   a hand-written infrastructure/ page's `last_reviewed` is > 6 months old
                (generated pages are exempt — their generators keep them current). Fix by
                re-verifying the page against reality and bumping the date (or via kb-ingest).
  NO-REVIEW-STAMP  a hand-written infrastructure/ page has no `last_reviewed` frontmatter —
                it's invisible to staleness tracking; add the stamp.
  NO-CENTROID   a framework page's country_iso3 has no entry in gen_public_site.COUNTRY —
                the country silently vanishes from the public AA map (real miss: Nicaragua).

Broken *markdown* links are covered by `lint-docs.yml` (mkdocs --strict), so they're
not re-checked here.

Usage:  python scripts/check_docs.py [--report docs-report.md]
Exit:   0 = clean · 2 = at least one finding
Needs:  pyyaml.
"""
from __future__ import annotations
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_doc_counts as gdc  # noqa: E402  (sibling module; reuse its COUNTS logic)

# The meta-docs: "how the KB works", not the content pages.
META_DOCS = [
    "README.md", "CLAUDE.md",
    "docs/DESIGN.md", "docs/INGESTION.md", "docs/ROADMAP.md", "docs/PRIVACY.md",
    "docs/README.md", "docs/glossary.md", "docs/PHASE2-SCOPE.md",
    "docs/repo-manifest.md", "docs/repo-audit.md", "docs/repo-doc-crosswalk.md",
    "infrastructure/automation.md", "scripts/README.md",
]

# Path-qualified references to project machinery. Anchored to the known dirs so we
# don't false-positive on prose. Trailing punctuation/backticks are trimmed.
REF_RE = re.compile(r"(scripts/[A-Za-z0-9_./-]+\.(?:py|sh)|\.github/workflows/[A-Za-z0-9_.-]+\.ya?ml)")

# Machinery that lives in the PRIVATE companion repo (ds-knowledge-base-internal), not here —
# the docs reference it correctly but the file is absent from this repo by design (D46).
EXTERNAL_REFS = {".github/workflows/drive-sync.yml"}


def find_missing_refs() -> list[tuple[str, str, str]]:
    rows = []
    for rel in META_DOCS:
        path = ROOT / rel
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        seen = set()
        for m in REF_RE.finditer(text):
            ref = m.group(1).rstrip(".,)`")
            if ref in seen or ref in EXTERNAL_REFS:
                continue
            seen.add(ref)
            if not (ROOT / ref).exists():
                rows.append((rel, "MISSING-REF", ref))
    return rows


STALE_AFTER_DAYS = 180
# Generated pages self-update on their own schedules; only hand-written reference pages rot silently.
_GENERATED_MARKERS = ("generated by", "DO NOT EDIT")


def find_stale_infra() -> list[tuple[str, str, str]]:
    import datetime
    import itertools

    import yaml

    rows = []
    today = datetime.date.today()
    # methods/ pages are hand-written reference too (same silent-rot class as infrastructure/)
    paths = itertools.chain(sorted((ROOT / "infrastructure").glob("*.md")),
                            sorted((ROOT / "methods").glob("*.md")))
    for path in paths:
        text = path.read_text(encoding="utf-8")
        head = "\n".join(text.splitlines()[:6])
        if any(m.lower() in head.lower() for m in _GENERATED_MARKERS):
            continue
        rel = path.relative_to(ROOT).as_posix()
        fm = {}
        if text.startswith("---"):
            try:
                fm = yaml.safe_load(text[3:text.find("\n---", 3)]) or {}
            except yaml.YAMLError:
                pass
        stamp = fm.get("last_reviewed")
        if not stamp:
            rows.append((rel, "NO-REVIEW-STAMP",
                         "no `last_reviewed` frontmatter — add it so staleness tracking sees this page"))
            continue
        try:
            age = (today - datetime.date.fromisoformat(str(stamp))).days
        except ValueError:
            rows.append((rel, "NO-REVIEW-STAMP", f"unparseable `last_reviewed: {stamp}` (want YYYY-MM-DD)"))
            continue
        if age > STALE_AFTER_DAYS:
            rows.append((rel, "STALE-INFRA",
                         f"`last_reviewed: {stamp}` is {age} days old — re-verify the page against reality and bump the date"))
    return rows


def find_missing_centroids() -> list[tuple[str, str, str]]:
    import yaml

    import gen_public_site as gps

    rows, seen = [], set()
    for path in sorted((ROOT / "frameworks").glob("*/*.md")):
        if path.name in ("README.md", "_TEMPLATE.md"):
            continue
        text = path.read_text(encoding="utf-8")
        if not text.startswith("---"):
            continue
        try:
            fm = yaml.safe_load(text[3:text.find("\n---", 3)]) or {}
        except yaml.YAMLError:
            continue
        if fm.get("content_type") != "framework":
            continue
        iso3s = fm.get("country_iso3")
        iso3s = iso3s if isinstance(iso3s, list) else [iso3s]
        for iso3 in iso3s:
            iso3 = str(iso3 or "").upper()
            if iso3 and iso3 not in gps.COUNTRY and iso3 not in seen:
                seen.add(iso3)
                rows.append((path.relative_to(ROOT).as_posix(), "NO-CENTROID",
                             f"`{iso3}` has no entry in gen_public_site.py COUNTRY/DIRECTIONS — "
                             "it will NOT render on the public AA map"))
    return rows


def find_stale_counts() -> list[tuple[str, str, str]]:
    rows = []
    body = gdc.block(gdc.counts())
    for path in gdc.TARGETS:
        if path.exists() and not gdc.is_current(path, body):
            rows.append((path.relative_to(ROOT).as_posix(), "STALE-COUNTS",
                         "COUNTS block disagrees with the live corpus — run `python scripts/gen_doc_counts.py`"))
    return rows


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--report", help="write the markdown report to this file")
    args = ap.parse_args()

    rows = find_stale_counts() + find_missing_refs() + find_stale_infra() + find_missing_centroids()

    lines = ["# KB meta-doc check", ""]
    if rows:
        lines.append(f"**{len(rows)} finding(s).**")
        lines += ["", "| doc | issue | detail |", "|---|---|---|"]
        lines += [f"| `{d}` | **{k}** | {v} |" for d, k, v in rows]
        lines += [
            "",
            "_Fix: `STALE-COUNTS` → run `python scripts/gen_doc_counts.py`. "
            "`MISSING-REF` → update the doc to the new path, or restore the file. "
            "`STALE-INFRA` / `NO-REVIEW-STAMP` → re-verify the infrastructure page and bump/add "
            "its `last_reviewed` date. "
            "Prose staleness (shipped phases, superseded rationale) is handled by the monthly "
            "`docs-audit.yml` Claude pass._",
        ]
    else:
        lines.append("✅ Meta-docs clean: counts current, all script/workflow references resolve.")
    report = "\n".join(lines) + "\n"

    print(report)
    if args.report:
        Path(args.report).write_text(report, encoding="utf-8")
    sys.exit(2 if rows else 0)


if __name__ == "__main__":
    main()
