#!/usr/bin/env python3
"""Mirror the Postgres DB schema into infrastructure/db-schema.md (read-only).

A point-in-time snapshot of the team's data assets: every schema → table →
columns + primary key, with a row-count estimate and on-disk size per table.
Connects read-only via ocha-stratus (never raw psycopg2). Also emits a small
machine-readable table list (`infrastructure/.db-tables.json`) that
`gen_dependency_graph.py` uses to wire DB tables into the dependency graph.

Refreshed daily by `.github/workflows/db-schema.yml`; safe to run locally if the
DSCI_AZ_DB_* env vars are set (+ PGSSLMODE=require).

Usage:  python scripts/gen_db_schema.py [--stage prod|dev]
"""
from __future__ import annotations
import argparse
import json
import os
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "infrastructure" / "db-schema.md"
JSON_OUT = ROOT / "infrastructure" / ".db-tables.json"

TABLES_SQL = """
SELECT n.nspname AS schema, c.relname AS tbl,
       c.reltuples::bigint AS est_rows,
       pg_total_relation_size(c.oid) AS bytes
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind = 'r'
  AND n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg\\_%'
ORDER BY n.nspname, c.relname;
"""
COLS_SQL = """
SELECT table_schema, table_name, column_name, data_type
FROM information_schema.columns
WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
  AND table_schema NOT LIKE 'pg\\_%'
ORDER BY table_schema, table_name, ordinal_position;
"""
PK_SQL = """
SELECT tc.table_schema AS s, tc.table_name AS t, kcu.column_name AS c
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu
  ON tc.constraint_name = kcu.constraint_name AND tc.table_schema = kcu.table_schema
WHERE tc.constraint_type = 'PRIMARY KEY'
  AND tc.table_schema NOT IN ('pg_catalog', 'information_schema')
  AND tc.table_schema NOT LIKE 'pg\\_%';
"""


def human(n: int) -> str:
    f = float(n)
    for u in ("B", "KB", "MB", "GB", "TB"):
        if f < 1024 or u == "TB":
            return f"{f:.0f} {u}" if u == "B" else f"{f:.1f} {u}"
        f /= 1024


def human_rows(n: int) -> str:
    if n < 0:
        return "?"          # never analyzed
    if n >= 1_000_000:
        return f"{n/1e6:.1f}M"
    if n >= 1_000:
        return f"{n/1e3:.1f}k"
    return str(n)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage", default="prod", choices=["prod", "dev"])
    args = ap.parse_args()
    os.environ.setdefault("PGSSLMODE", "require")

    try:
        import ocha_stratus as stratus
        from sqlalchemy import text
    except ImportError:
        sys.exit("Needs ocha-stratus + sqlalchemy (pip install ocha-stratus).")

    try:
        engine = stratus.get_engine(stage=args.stage)
        with engine.connect() as conn:
            tables = conn.execute(text(TABLES_SQL)).fetchall()
            cols = conn.execute(text(COLS_SQL)).fetchall()
            pks = conn.execute(text(PK_SQL)).fetchall()
    except Exception as e:
        sys.exit(f"DB introspection failed ({type(e).__name__}: {e}). "
                 "Check DSCI_AZ_DB_* env / secrets, PGSSLMODE=require, and network access to Azure PG.")

    cols_by = defaultdict(list)
    for s, t, c, dt in cols:
        cols_by[(s, t)].append((c, dt))
    pk_by = defaultdict(set)
    for s, t, c in pks:
        pk_by[(s, t)].add(c)

    by_schema = defaultdict(list)
    json_tables = {}
    for s, t, rows, b in tables:
        by_schema[s].append((t, rows, b))
        json_tables[f"{s}.{t}"] = {"rows": int(rows), "bytes": int(b),
                                   "columns": [c for c, _ in cols_by[(s, t)]]}

    n_tables = len(tables)
    total_bytes = sum(b for *_, b in tables)
    L = ["<!-- generated by scripts/gen_db_schema.py — a read-only snapshot of the live DB; do not edit -->",
         "", "# Database schema", "",
         f"Read-only snapshot of the Postgres **{args.stage}** database (via `ocha-stratus`), refreshed daily by "
         "`.github/workflows/db-schema.yml`. The team's data-asset map; row counts are planner estimates "
         "(`reltuples`), sizes include indexes + TOAST. These tables are nodes in "
         "`dependency-graph.md` (pipelines write them, apps read them).", "",
         f"**{len(by_schema)} schemas · {n_tables} tables · {human(total_bytes)} total.**", ""]
    for s in sorted(by_schema):
        rows = sorted(by_schema[s], key=lambda r: -r[2])
        sb = sum(b for *_, b in rows)
        L += [f"## `{s}` — {len(rows)} tables · {human(sb)}", "",
              "| table | rows (est) | size | columns |", "|---|--:|--:|---|"]
        for t, r, b in rows:
            cl = cols_by[(s, t)]
            pk = pk_by[(s, t)]
            colstr = ", ".join((f"**{c}**" if c in pk else c) + f" `{dt}`" for c, dt in cl)
            colcell = f"<details><summary>{len(cl)} cols</summary>{colstr}</details>" if cl else "—"
            L.append(f"| `{t}` | {human_rows(r)} | {human(b)} | {colcell} |")
        L.append("")
    L.append("_**bold** = primary key. Regenerate: `python scripts/gen_db_schema.py`._")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    JSON_OUT.write_text(json.dumps(json_tables, indent=0), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(by_schema)} schemas, {n_tables} tables, {human(total_bytes)}.")


if __name__ == "__main__":
    main()
