#!/usr/bin/env python3
"""Regenerate the KB feedback issue form with a current list of pages.

GitHub issue forms can't do cascading dropdowns (the 2nd can't filter by the
1st), so we use two: a static **Content type** dropdown + a generated
**Specific item** dropdown listing every framework/pipeline/app (type-prefixed,
so it reads like type→thing). Run after each ingest batch alongside
`gen_catalog.py` so the item list stays current.

Usage:  python scripts/gen_issue_form.py   (from repo root)
"""
from __future__ import annotations
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / ".github" / "ISSUE_TEMPLATE" / "kb-feedback.yml"


def items() -> list[str]:
    out = []
    for d in sorted(p for p in (ROOT / "frameworks").iterdir() if p.is_dir()):
        out.append(f"framework · {d.name}")
    for kind in ("pipeline", "app"):
        for f in sorted((ROOT / (kind + "s")).glob("*.md")):
            if f.name in ("_TEMPLATE.md", "README.md"):
                continue
            out.append(f"{kind} · {f.stem}")
    return out


def yaml_list(opts: list[str], indent="        ") -> str:
    return "\n".join(f'{indent}- "{o}"' for o in opts)


def main() -> None:
    specific = ["— general / not page-specific —"] + items() + ["— other / not listed —"]
    form = f"""name: KB error or feedback
description: Flag something wrong, stale, or missing in the knowledge base — or suggest an improvement.
title: "[kb] "
labels: ["kb-feedback"]
# NOTE: generated by scripts/gen_issue_form.py — the "Specific item" options are
# rebuilt from the corpus after each ingest batch. Edit the script, not this file.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for improving the KB. For a quick fix you can edit the page directly (open a PR) — use this for things you can't fix yourself, or to flag for the owner.
  - type: dropdown
    id: kind
    attributes:
      label: Type
      options:
        - Error — a fact/number/trigger is wrong
        - Stale — out of date (newer framework version, changed code)
        - Missing — a framework/pipeline/app/fact that should be here isn't
        - Suggestion — structure, schema, or workflow improvement
        - Question
    validations:
      required: true
  - type: dropdown
    id: content_type
    attributes:
      label: Content type
      description: Which part of the KB is this about?
      options:
        - framework
        - pipeline
        - app
        - method
        - infrastructure / deployment
        - catalog / index
        - schema / conventions
        - other / general
    validations:
      required: true
  - type: dropdown
    id: item
    attributes:
      label: Specific item
      description: The exact page, if it's about one (type-prefixed). Pick "general" if not page-specific, or "other / not listed" if missing.
      options:
{yaml_list(specific)}
    validations:
      required: false
  - type: textarea
    id: detail
    attributes:
      label: What's wrong / what you'd change
      description: Be specific. For an **error**, point to the authoritative source (the framework PDF, the code path) so it can be reconciled — that's how the KB stays trustworthy.
    validations:
      required: true
"""
    OUT.write_text(form, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(items())} specific items.")


if __name__ == "__main__":
    main()
