#!/usr/bin/env python3
"""Generate a README index for every framework folder from its version pages.

Each `frameworks/<id>/README.md` is the folder's landing page: a one-line
summary (from the current version's `## Summary`), the current version + status,
operated-by, a version-lineage table, and sibling-framework links. Generated —
edit the version pages, not the README. Run after each ingest batch alongside
`gen_catalog.py`.

Usage:  python scripts/gen_framework_readmes.py   (from repo root)
"""
from __future__ import annotations
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("Needs pyyaml:  uv pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
FW = ROOT / "frameworks"
MARKER = "<!-- generated by scripts/gen_framework_readmes.py — edit the version pages, not here -->"
ISO3 = {
    "AFG": "Afghanistan", "BFA": "Burkina Faso", "BGD": "Bangladesh", "COD": "DR Congo",
    "CUB": "Cuba", "MOZ": "Mozambique", "MRT": "Mauritania", "NER": "Niger", "NGA": "Nigeria",
    "NPL": "Nepal", "PHL": "Philippines", "TCD": "Chad", "HTI": "Haiti", "SLV": "El Salvador",
    "GTM": "Guatemala", "HND": "Honduras", "ETH": "Ethiopia", "SSD": "South Sudan",
    "MDG": "Madagascar", "SAHEL": "Sahel",
}
ACTIVE = ("triggered", "endorsed", "development", "pre-development")  # not superseded/retired


def fm_and_summary(path: Path):
    t = path.read_text(encoding="utf-8")
    end = t.find("\n---", 3)
    try:
        fm = yaml.safe_load(t[3:end]) or {}
    except yaml.YAMLError:
        return None, ""
    body = t[end:]
    summary = ""
    i = body.find("## Summary")
    if i != -1:
        seg = body[i + len("## Summary"):]
        nxt = seg.find("\n## ")
        seg = seg[:nxt] if nxt != -1 else seg
        for para in seg.strip().split("\n\n"):
            p = para.strip()
            if p and not p.startswith(("<!--", ">")):
                summary = " ".join(p.split())
                break
    return fm, summary


def vkey(v: str):
    # dated versions sort chronologically; non-dated (e.g. "development") sort last
    s = str(v)
    return (0, s) if s[:4].isdigit() else (1, s)


def fmt_funding(v):
    return f"${v / 1e6:.1f}M" if isinstance(v, (int, float)) and v > 0 else "—"


def fmt_activated(acts):
    acts = acts or []
    dates = [str(a.get("date", "")) for a in acts if isinstance(a, dict) and a.get("date")]
    return "✅ " + ", ".join(dates) if dates else "—"


def country_str(iso):
    vals = iso if isinstance(iso, list) else [iso]
    return "/".join(ISO3.get(str(v), str(v)) for v in vals if v)


def main() -> None:
    # gather: folder -> [(version_str, fm, summary, relpath)]
    folders = {}
    name_prefix = {}  # folder -> prefix before first '-'
    for d in sorted(p for p in FW.iterdir() if p.is_dir()):
        versions = []
        for page in sorted(d.glob("*.md")):
            if page.name == "README.md":
                continue
            fm, summ = fm_and_summary(page)
            if not fm or fm.get("content_type") != "framework":
                continue
            versions.append((str(fm.get("version", page.stem)), fm, summ, page.name))
        if versions:
            folders[d.name] = sorted(versions, key=lambda x: vkey(x[0]))
            name_prefix[d.name] = d.name.split("-")[0]

    written = 0
    for fid, versions in folders.items():
        # current = latest non-superseded/retired version; else latest
        actives = [v for v in versions if v[1].get("status") in ACTIVE]
        current = (actives or versions)[-1]
        cv, cfm, csumm, cfile = current
        iso = country_str(cfm.get("country_iso3"))
        hazard = str(cfm.get("hazard", "")).replace("-", " ")
        operated = cfm.get("operated_by")
        repo = cfm.get("source_repo", "")

        lines = [MARKER, "", f"# {iso} {hazard} — `{fid}`", ""]
        if csumm:
            lines += [csumm, ""]
        cur_line = f"**Current version:** [{cv}]({cfile}) · status: **{cfm.get('status','?')}**"
        if operated:
            cur_line += f" · live trigger operated by *{operated}*"
        if repo:
            cur_line += f" · repo `{repo}`"
        lines += [cur_line, "", "## Versions", "",
                  "| version | status | doc date | $ pre-arr. | activated |",
                  "|---|---|---|--:|---|"]
        for v, fm, _, fn in versions:
            mark = "**" if (v, fn) == (cv, cfile) else ""
            label = f"{mark}[{v}]({fn}){mark}"
            doc = fm.get("framework_doc")
            dd = fm.get("framework_doc_date") or "—"
            doccell = f"[{dd}]({doc})" if doc else str(dd)
            lines.append(f"| {label} | {fm.get('status','?')} | {doccell} | "
                         f"{fmt_funding(fm.get('prearranged_funding_usd'))} | "
                         f"{fmt_activated(fm.get('activations'))} |")
        # siblings: same name prefix, different folder
        sibs = sorted(f for f in folders if f != fid and name_prefix[f] == name_prefix[fid])
        if sibs:
            lines += ["", "**Related:** " + ", ".join(f"[`{s}`]({'../' + s})" for s in sibs)]
        (FW / fid / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
        written += 1

    print(f"Wrote {written} framework README index pages.")


if __name__ == "__main__":
    main()
