#!/usr/bin/env python3
"""Inject the live corpus counts into ROADMAP.md (and any doc) between markers.

The meta-docs used to hand-type counts ("34 frameworks, 16 pipelines, …") and
they rotted the moment a page was added. This makes the counts a *generated*
fact — the same discipline as catalog.md — so they can't disagree with reality.

It rewrites whatever sits between:
    <!-- COUNTS:START -->  …generated…  <!-- COUNTS:END -->
in each target doc. Source of truth is the pages on disk (content_type + folder),
not catalog.md (which can itself lag until regenerated).

Usage:  python scripts/gen_doc_counts.py [--check]   (run from repo root)
        --check : exit 2 if any target's COUNTS block is out of date (CI guard),
                  writing nothing. Else rewrite in place.
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("Needs pyyaml:  uv pip install pyyaml  (or pip install pyyaml)")

ROOT = Path(__file__).resolve().parent.parent
START, END = "<!-- COUNTS:START -->", "<!-- COUNTS:END -->"

# Docs that carry a COUNTS block. (A doc without the markers is silently skipped.)
TARGETS = [ROOT / "docs" / "ROADMAP.md"]


def parse_frontmatter(path: Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    try:
        return yaml.safe_load(text[3:end]) or {}
    except yaml.YAMLError:
        return None


def _pages(folder: str) -> list[Path]:
    d = ROOT / folder
    if not d.exists():
        return []
    return [p for p in sorted(d.rglob("*.md"))
            if p.name not in ("_TEMPLATE.md", "README.md")]


def counts() -> dict[str, int]:
    fw_versions, fw_names = 0, set()
    for p in _pages("frameworks"):
        fm = parse_frontmatter(p)
        if fm and fm.get("content_type") == "framework":
            fw_versions += 1
            fw_names.add(fm.get("framework", p.parent.name))
    return {
        "frameworks": len(fw_names),
        "framework_versions": fw_versions,
        "analysis": len(_pages("analysis")),
        "pipelines": len(_pages("pipelines")),
        "apps": len(_pages("apps")),
        "libraries": len([p for p in _pages("infrastructure/libs")]),
    }


def block(c: dict[str, int]) -> str:
    """The generated snapshot line (no date — so it only commits when counts change)."""
    return (
        f"**Corpus snapshot** (generated by `scripts/gen_doc_counts.py` — do not hand-edit): "
        f"**{c['frameworks']} frameworks** ({c['framework_versions']} versions) · "
        f"**{c['analysis']} analysis** · **{c['pipelines']} pipelines** · "
        f"**{c['apps']} apps** · **{c['libraries']} libraries**. "
        f"Authoritative per-item lists: [`catalog.md`](../catalog.md), the registries under "
        f"[`infrastructure/`](../infrastructure/)."
    )


def apply(path: Path, body: str) -> bool:
    """Replace the COUNTS block in `path`. Returns True if the file changed."""
    text = path.read_text(encoding="utf-8")
    i, j = text.find(START), text.find(END)
    if i == -1 or j == -1 or j < i:
        return False  # no markers → not a target
    new = text[:i] + START + "\n" + body + "\n" + text[j:]
    if new == text:
        return False
    path.write_text(new, encoding="utf-8")
    return True


def is_current(path: Path, body: str) -> bool:
    text = path.read_text(encoding="utf-8")
    i, j = text.find(START), text.find(END)
    if i == -1 or j == -1:
        return True  # no markers → nothing to be stale
    current = text[i + len(START):j].strip()
    return current == body.strip()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 2 if any COUNTS block is out of date; write nothing")
    args = ap.parse_args()

    c = counts()
    body = block(c)
    stale, changed = [], []
    for path in TARGETS:
        if not path.exists():
            continue
        if args.check:
            if not is_current(path, body):
                stale.append(path.relative_to(ROOT).as_posix())
        elif apply(path, body):
            changed.append(path.relative_to(ROOT).as_posix())

    if args.check:
        if stale:
            print("Out-of-date COUNTS block(s) — run `python scripts/gen_doc_counts.py`:")
            for s in stale:
                print(f"  - {s}")
            sys.exit(2)
        print("✅ COUNTS blocks current.")
        return

    summary = ", ".join(f"{k} {v}" for k, v in c.items())
    if changed:
        print(f"Updated COUNTS in: {', '.join(changed)}  ({summary})")
    else:
        print(f"COUNTS already current ({summary}).")


if __name__ == "__main__":
    main()
