#!/usr/bin/env python3
"""Audit every spoke repo's GitHub visibility → infrastructure/spoke-repos.md.

Scans the `source_repo` of every content page (frameworks / pipelines / apps /
analysis), resolves each distinct `ocha-dap/<repo>` slug's visibility via `gh`,
and writes a registry that **marks the private spokes**. Private spokes are the
ones the drift bot can't see with the default CI token (it reports them
NO-ACCESS) and that readers can't click through to without org access.

Run locally where your `gh` PAT can read private repos (in CI the default
GITHUB_TOKEN can't, so private repos resolve as `unknown`). Snapshot, like
db-schema.md.

Usage:  python scripts/gen_spoke_repos.py   (from repo root)
Needs:  gh CLI authenticated; pyyaml.
"""
from __future__ import annotations
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("Needs pyyaml:  uv pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
SCAN = ["frameworks", "pipelines", "apps", "analysis"]
SLUG_RE = re.compile(r"(?:ocha-dap|OCHA-DAP)/[A-Za-z0-9._-]+")
OUT = ROOT / "infrastructure" / "spoke-repos.md"


def frontmatter(path: Path) -> dict | None:
    t = path.read_text(encoding="utf-8")
    if not t.startswith("---"):
        return None
    end = t.find("\n---", 3)
    if end == -1:
        return None
    try:
        return yaml.safe_load(t[3:end]) or {}
    except yaml.YAMLError:
        return None


def slugs_in(value) -> list[str]:
    """Pull every ocha-dap/<repo> slug out of a source_repo value, normalized."""
    out = []
    for m in SLUG_RE.findall(str(value or "")):
        slug = m.lower().rstrip(".")              # strip trailing-period noise
        slug = "ocha-dap/" + slug.split("/", 1)[1]  # normalize org case
        if slug not in out:
            out.append(slug)
    return out


def visibility(slug: str) -> str:
    p = subprocess.run(["gh", "api", f"repos/{slug}", "--jq", ".visibility"],
                       capture_output=True, text=True)
    v = p.stdout.strip()
    if p.returncode == 0 and v:
        return v
    return "unknown"  # unreadable with this token (private + no access, or deleted)


def main() -> None:
    repo_pages: dict[str, list[str]] = defaultdict(list)
    for d in SCAN:
        base = ROOT / d
        if not base.exists():
            continue
        for path in sorted(base.rglob("*.md")):
            if path.name in ("_TEMPLATE.md", "README.md"):
                continue
            fm = frontmatter(path)
            if not fm:
                continue
            rel = path.relative_to(ROOT).as_posix()
            for slug in slugs_in(fm.get("source_repo")):
                repo_pages[slug].append(rel)

    vis = {slug: visibility(slug) for slug in sorted(repo_pages)}
    order = {"private": 0, "internal": 1, "unknown": 2, "public": 3}
    rows = sorted(repo_pages, key=lambda s: (order.get(vis[s], 9), s))
    n_private = sum(1 for s in rows if vis[s] in ("private", "internal"))
    n_unknown = sum(1 for s in rows if vis[s] == "unknown")

    def badge(v: str) -> str:
        return {"private": "🔒 **private**", "internal": "🔒 **internal**",
                "public": "🌐 public", "unknown": "❓ unknown"}.get(v, v)

    L = ["<!-- generated by scripts/gen_spoke_repos.py — a snapshot of spoke-repo visibility; do not edit -->",
         "", "# Spoke repo visibility", "",
         "Every distinct `source_repo` referenced by a KB page, with its GitHub visibility. "
         "**🔒 private spokes** can't be read by the drift bot's default CI token (it reports them "
         "`NO-ACCESS`, not drift) and readers need org access to follow their links. "
         "Regenerate with `python scripts/gen_spoke_repos.py` (run locally — a PAT with org "
         "`repo:read` is needed to resolve private repos; in CI they show as `unknown`).", "",
         f"**{len(rows)} spokes · {n_private} private · {n_unknown} unknown.**", "",
         "| repo | visibility | pages |", "|---|---|---|"]
    for s in rows:
        pages = ", ".join(f"`{p}`" for p in sorted(repo_pages[s]))
        L.append(f"| [`{s}`](https://github.com/{s}) | {badge(vis[s])} | {pages} |")
    L.append("")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(rows)} spokes, {n_private} private, {n_unknown} unknown.")


if __name__ == "__main__":
    main()
