#!/usr/bin/env python3
"""Regenerate catalog-global.md — ALL anticipatory-action frameworks across ALL orgs.

One row per framework: the OCHA/CERF portfolio (frameworks/, latest version per
framework) + every external org's page (external-frameworks/<org>/). Reads ONLY the
common-core fields both schemas share (D76: core ⊂ OCHA schema), so external pages'
looseness never touches OCHA tooling, and this generator never needs the OCHA extras.

Usage:  python scripts/gen_global_catalog.py   (run from repo root; needs pyyaml)
"""
from __future__ import annotations

import datetime
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("Needs pyyaml:  uv pip install pyyaml  (or pip install pyyaml)")

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "catalog-global.md"


def parse_frontmatter(path: Path) -> dict | None:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    try:
        return yaml.safe_load(text[3:end]) or {}
    except yaml.YAMLError:
        return None


def as_list(v) -> list:
    if v is None:
        return []
    return v if isinstance(v, list) else [v]


def fmt_usd(v) -> str:
    if not isinstance(v, (int, float)) or not v:
        return "—"
    return f"${v / 1e6:.1f}M" if v >= 1e6 else f"${v / 1e3:.0f}k"


def core_row(org: str, fm: dict, rel: str) -> dict:
    countries = ", ".join(str(c) for c in as_list(fm.get("country_iso3")))
    acts = as_list(fm.get("activations"))
    return {
        "org": org,
        "id": str(fm.get("framework") or Path(rel).stem),
        "rel": rel,
        "countries": countries or "—",
        "hazard": str(fm.get("hazard") or "—"),
        "status": str(fm.get("status") or "unknown"),
        "funding": fmt_usd(fm.get("prearranged_funding_usd")),
        "n_activations": len(acts),
        "doc_date": str(fm.get("framework_doc_date") or "—")[:10],
    }


def latest_ocha_versions() -> list[dict]:
    """One row per OCHA framework — the latest dated version page (dated > drafts)."""
    rows = []
    fw_root = ROOT / "frameworks"
    for fw_dir in sorted(p for p in fw_root.iterdir() if p.is_dir()):
        pages = [p for p in fw_dir.glob("*.md") if p.name != "README.md"]
        if not pages:
            continue
        dated = sorted(p for p in pages if p.stem[:4].isdigit())
        page = dated[-1] if dated else sorted(pages)[-1]
        fm = parse_frontmatter(page)
        if not fm or fm.get("content_type") != "framework":
            continue
        rows.append(core_row("OCHA/CERF", fm, page.relative_to(ROOT).as_posix()))
    return rows


def external_rows() -> list[dict]:
    rows = []
    ext_root = ROOT / "external-frameworks"
    if not ext_root.exists():
        return rows
    for page in sorted(ext_root.glob("*/*.md")):
        if page.name in ("README.md",):
            continue
        fm = parse_frontmatter(page)
        if not fm or fm.get("content_type") != "framework-external":
            continue
        rows.append(core_row(str(fm.get("org") or page.parent.name.upper()),
                             fm, page.relative_to(ROOT).as_posix()))
    return rows


def main() -> None:
    rows = latest_ocha_versions() + external_rows()
    rows.sort(key=lambda r: (r["org"] != "OCHA/CERF", r["org"], r["countries"], r["hazard"]))
    orgs = sorted({r["org"] for r in rows})
    lines = [
        "# Global AA framework catalog — all organisations",
        "",
        "_Generated by `scripts/gen_global_catalog.py` — do not edit by hand. One row per",
        "framework: the OCHA/CERF portfolio (latest version each, full detail in",
        "[`catalog.md`](catalog.md)) + external orgs' frameworks",
        "([`external-frameworks/`](external-frameworks/README.md), looser pages by design)._",
        "",
        f"_{len(rows)} frameworks across {len(orgs)} orgs ({', '.join(orgs)})."
        f" Updated {datetime.date.today().isoformat()}._",
        "",
        "| org | framework | countries | hazard | status | pre-arr. funding | activations | doc date |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['org']} | [{r['id']}]({r['rel']}) | {r['countries']} | {r['hazard']} "
            f"| {r['status']} | {r['funding']} | {r['n_activations']} | {r['doc_date']} |")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"catalog-global.md: {len(rows)} rows ({len(orgs)} orgs)")


if __name__ == "__main__":
    main()
